@extends('admin.template.header')


@section('title', $title)

@section('css')
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
<link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
@endsection

@section('body')

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-1"></div>
        <div class="col-sm-8">

            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">{{$header_title}}</h6>
                </div>
                <div class="card-body">
                    <!-- Form Start Here -->
                    <form action="{{route('bts.update')}}" method="post" autocomplete="off">
                        @csrf

                        <input type="hidden" name="id_spk" value="{{$spk->id}}">

                        <div class="form-group">
                            <label>Nama BTS</label>
                            <!-- harus dropdown ajax -->
                            <div class="input-group">
                                <select class="form-control select-2" id="select2-bts" name="id_bts[]" multiple>
                                    <option></option>
                                    @foreach($listBTS as $bts)
                                    <option value="{{$bts->id}}" {{in_array($bts->id, $bts_old) ? "selected" : ""}}>{{$bts->nama_bts}}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label>No. SPK</label>
                            <input type="text" name="no_spk" class="form-control" value="{{$spk->no_spk}}" readonly>
                            <small>*auto generated by system</small>
                        </div>

                        <div class="form-group">
                            <label for="datepicker">Tanggal Perbaikan</label>
                            <input id="datepicker" name="tgl_pekerjaan" value="{{$spk->tgl_pekerjaan}}" data-date-format="mm/dd/yyyy">
                            <div class="input-group-addon">
                                <span class="glyphicon glyphicon-th"></span>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="timepicker">Jam Mulai</label>
                            <input type="text" name="jam_mulai" value="{{$spk->jam_mulai}}" class="form-control time-picker">
                            <div class="input-group-addon">
                                <span class="glyphicon glyphicon-th"></span>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="timepicker">Jam Selesai</label>
                            <input type="text" name="jam_selesai" value="{{$spk->jam_selesai}}" class="form-control time-picker">
                            <div class="input-group-addon">
                                <span class="glyphicon glyphicon-th"></span>
                            </div>
                        </div>

                        <div class="form-group">
                            <label>Jenis Perbaikan</label>
                            <select name="jenis_perbaikan" class="custom-select">
                                <option value="1" {!! $spk->jenis_pekerjaan == 1 ? "selected" : "" !!}>Instalasi Baru</option>
                                <option value="2" {!! $spk->jenis_pekerjaan == 2 ? "selected" : "" !!} >Perbaikan Client</option>
                                <option value="3" {!! $spk->jenis_pekerjaan == 3 ? "selected" : "" !!} >Maintenance BTS</option>
                                <option value="4" {!! $spk->jenis_pekerjaan == 4 ? "selected" : "" !!} >Pencabutan Perangkat</option>
                            </select>
                        </div>

                        <div class="form-group">
                            <label>Keterangan</label>
                            <textarea class="form-control" name="ket_pekerjaan" rows="3">{{$spk->ket_pekerjaan}}</textarea>
                        </div>


                        <div class="form-group">
                            <label>Nama Teknisi</label>
                            <!-- harus dropdown ajax -->
                            <div class="input-group">
                                <select class="form-control select-2" id="teknisi" name="teknisi[]" multiple>
                                    <option></option>

                                    @foreach($list_teknisi as $t)
                                    <option value="{{$t->id}}" {{in_array($t->id, $ikr) ? "selected" : "" }}>{{$t->nama}}</option>
                                    @endforeach

                                </select>
                            </div>
                        </div>

                        <div class="form-group center">
                            <input type="submit" name="submit" class="btn btn-success" value="Update SPK">
                            <a href="{{url()->previous()}}" class="btn btn-primary">Kembali</a>
                        </div>

                    </form>


                </div>
            </div>

        </div>


    </div>
    <!-- DataTales Example -->



</div>

@endsection

@push('javascript')
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
<script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.10/jquery.mask.js"></script>

<script>
    $(document).ready(function($) {
        $('.select-2').select2({
            placeholder: "Pilih salah satu"
        });

    });

    $('#datepicker').datepicker({
        uiLibrary: 'bootstrap4',
    });

    $('.time-picker').mask('00:00');
</script>

@endpush