@extends('admin.template.header')


@section('title', $title)



@section('body')

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-1"></div>
        <div class="col-sm-8">

            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">{{$header_title}}</h6>
                </div>
                <div class="card-body">
                    <!-- Form Start Here -->
                    <form action="#" method="post">

                        <div class="form-group">
                            <label>Nama Pelanggan</label>
                            <input type="text" name="nama_pelanggan" class="form-control" value="{{ $spk->nama }}" disabled>
                        </div>

                        <div class="form-group">
                            <label>No. SPK</label>
                            <input type="text" name="no_spk" class="form-control" value="{{ $spk->no_spk }}" disabled>
                            <small>*auto generated by system</small>
                        </div>

                        <div class="form-group">
                            <label>No. Pelanggan</label>
                            <input type="text" name="no_pelanggan" value="{{ $spk->no_pelanggan }}" class="form-control" disabled>
                        </div>

                        <div class="form-group">
                            <label>ATTN</label>
                            <input type="text" name="attn" class="form-control" value="{{ $spk->attn }}" placeholder="" disabled>
                        </div>

                        <div class="form-group">
                            <label for="datepicker">Tanggal Pengerjaan</label>
                            <input id="datepicker" class="form-control" name="tgl_pekerjaan" value="{{ $spk->tgl_pekerjaan }}" data-date-format="mm/dd/yyyy" disabled>
                            <div class="input-group-addon">
                                <span class="glyphicon glyphicon-th"></span>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="timepicker">Jam Mulai</label>
                            <input type="text" name="jam_mulai" class="form-control time-picker" value="{{ $spk->jam_mulai }}" disabled>
                            <div class="input-group-addon">
                                <span class="glyphicon glyphicon-th"></span>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="timepicker">Jam Selesai</label>
                            <input type="text" name="jam_selesai" class="form-control time-picker" value="{{ $spk->jam_selesai }}" disabled>
                            <div class="input-group-addon">
                                <span class="glyphicon glyphicon-th"></span>
                            </div>
                        </div>

                        <div class="form-group">
                            <label>Jenis Perbaikan</label>
                            <select name="jenis_perbaikan" class="custom-select" disabled>
                                <!-- <option value="" hidden selected>Pilih salah satu</option> -->
                                <option value="1" {!! $spk->jenis_pekerjaan == 1 ? "selected" : "" !!}>Instalasi Baru</option>
                                <option value="2" {!! $spk->jenis_pekerjaan == 2 ? "selected" : "" !!} >Perbaikan Client</option>
                                <option value="3" {!! $spk->jenis_pekerjaan == 3 ? "selected" : "" !!} >Maintenance BTS</option>
                                <option value="4" {!! $spk->jenis_pekerjaan == 4 ? "selected" : "" !!} >Pencabutan Perangkat</option>
                            </select>
                        </div>

                        <div class="form-group">
                            <label>Keterangan</label>
                            <textarea class="form-control" name="ket_pekerjaan" rows="3" disabled>{{ $spk->ket_pekerjaan }}</textarea>
                        </div>

                        <div class="form-group">
                            <label for="exampleInputEmail1">BTS</label>
                            <input type="text" name="bts" id="bts" value="{{ $spk->nama_bts }}" class="form-control" disabled>
                        </div>

                        <div class="form-group">
                            <label for="exampleInputEmail1">AP</label>
                            <input type="text" name="ap" id="ap" value="{{ $spk->nama_ap }}" class="form-control" disabled>
                        </div>

                        <div class="form-group">
                            @foreach($teknisi as $tek)
                            <label>Nama Teknisi #{{$loop->iteration}}</label>
                            <input type="text" name="nama_teknisi" value="{{$tek->nama}}" class="form-control" disabled>
                            @endforeach
                        </div>

                        <div class="form-group center">
                            <a href="{{route('maintenance.edit', $spk->id)}}" class="btn btn-warning">Edit SPK</a>
                            <a href="{{route('maintenance.delete', $spk->id)}}" class="btn btn-danger">Batalkan SPK</a>
                            <!-- <a href="{{url()->previous()}}" class="btn btn-primary">Kembali</a> -->
                        </div>

                    </form>



                </div>
            </div>

        </div>


    </div>


</div>

@endsection

@push('javascript')
@endpush