@extends('admin.template.header')


@section('title', $title)

@section('css')
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
<link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
@endsection

@section('body')

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-1"></div>
        <div class="col-sm-8">

            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">{{$header_title}}</h6>
                </div>
                <div class="card-body">
                    <!-- Form Start Here -->
                    <form action="{{route('maintenance.update')}}" method="post" autocomplete="off">
                        @csrf

                        <input type="hidden" name="id_spk" value="{{$id_spk}}">

                        <div class="form-group">
                            <label>Nama Pelanggan</label>
                            <!-- harus dropdown ajax -->
                            <div class="input-group">
                                <select class="form-control select-2" id="select2-customer" name="nama_pelanggan">
                                    <option></option>
                                    @foreach($customers as $customer)
                                    <option value="{{$customer->id}}" {{$customer->id == $spk->id_customer ? "selected" : ""}}>{{$customer->nama}}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label>No. SPK</label>
                            <input type="text" name="no_spk" class="form-control" value="{{$spk->no_spk}}" readonly>
                            <small>*auto generated by system</small>
                        </div>

                        <div class="form-group">
                            <label>No. Pelanggan</label>
                            <input type="text" name="no_pelanggan" id="no_pelanggan" class="form-control" readonly>
                        </div>

                        <div class="form-group">
                            <label>ATTN</label>
                            <input type="text" name="attn" class="form-control" placeholder="" value="{{$spk->attn}}">
                        </div>

                        <div class="form-group">
                            <label for="datepicker">Tanggal Perbaikan</label>
                            <input id="datepicker" name="tgl_pekerjaan" value="{{$spk->tgl_pekerjaan}}" data-date-format="mm/dd/yyyy">
                            <div class="input-group-addon">
                                <span class="glyphicon glyphicon-th"></span>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="timepicker">Jam Mulai</label>
                            <input type="text" name="jam_mulai" value="{{$spk->jam_mulai}}" class="form-control time-picker">
                            <div class="input-group-addon">
                                <span class="glyphicon glyphicon-th"></span>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="timepicker">Jam Selesai</label>
                            <input type="text" name="jam_selesai" value="{{$spk->jam_selesai}}" class="form-control time-picker" readonly>
                            <div class="input-group-addon">
                                <span class="glyphicon glyphicon-th"></span>
                            </div>
                        </div>

                        <div class="form-group">
                            <label>Jenis Perbaikan</label>
                            <select name="jenis_perbaikan" class="custom-select">
                                <option value="1" {!! $spk->jenis_pekerjaan == 1 ? "selected" : "" !!}>Instalasi Baru</option>
                                <option value="2" {!! $spk->jenis_pekerjaan == 2 ? "selected" : "" !!} >Perbaikan Client</option>
                                <option value="3" {!! $spk->jenis_pekerjaan == 3 ? "selected" : "" !!} >Maintenance BTS</option>
                                <option value="4" {!! $spk->jenis_pekerjaan == 4 ? "selected" : "" !!} >Pencabutan Perangkat</option>
                            </select>
                        </div>

                        <div class="form-group">
                            <label>Keterangan</label>
                            <textarea class="form-control" name="ket_pekerjaan" rows="3">{{$spk->ket_pekerjaan}}</textarea>
                        </div>


                        <div class="form-group">
                            <label>Nama Teknisi</label>
                            <!-- harus dropdown ajax -->
                            <div class="input-group">
                                <select class="form-control select-2" id="teknisi" name="teknisi[]" multiple>
                                    <option></option>

                                    @foreach($teknisi as $t)
                                    <option value="{{$t->id}}" {{in_array($t->id, $ikr) ? "selected" : "" }}>{{$t->nama}}</option>
                                    @endforeach

                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="exampleInputEmail1">BTS</label>
                            <input type="text" name="bts" id="bts" class="form-control" value="{{$spk->nama_bts}}" readonly>
                        </div>

                        <div class="form-group">
                            <label for="exampleInputEmail1">AP</label>
                            <input type="text" name="ap" id="ap" class="form-control" value="{{$spk->nama_ap}}" readonly>
                        </div>


                        <div class="form-group center">
                            <input type="submit" name="submit" class="btn btn-success" value="Update SPK">
                            <a href="{{url()->previous()}}" class="btn btn-primary">Kembali</a>
                        </div>

                    </form>


                </div>
            </div>

        </div>


    </div>
    <!-- DataTales Example -->
</div>

@endsection

@push('javascript')
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
<script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.10/jquery.mask.js"></script>

<script>
    $(document).ready(function($) {
        $('.select-2').select2({
            placeholder: "Pilih salah satu"
        });

        $.fn.myfunction = function() {
            var id_customer = $('#select2-customer').val();

            if (id_customer != "") {
                $.ajax({
                    type: "GET",
                    url: "{{route('getDataCustomer')}}",
                    data: {
                        id: id_customer
                    },
                    success: function(data) {
                        console.log(data);
                        $('#no_pelanggan').val(data.no_pelanggan);
                        $('#bts').val(data.bts);
                        $('#ap').val(data.ap);
                    }
                })
            }

        };

        $.fn.myfunction();

        $('#select2-customer').change(function() {
            $.fn.myfunction();
        });

    });

    $('#datepicker').datepicker({
        uiLibrary: 'bootstrap4',
    });

    $('.time-picker').mask('00:00');
</script>

@endpush